# https://youdianzhishi.com/
# olaf.luo@foxmail.com
# Rowan Luo
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: cni
  name: cni
spec:
  selector:
    matchLabels:
      app: cni
  template:
    metadata:
      labels:
        app: cni
    spec:
      containers:
      - image: 192.168.2.100:5000/nettool
        name: nettoolbox

