#/bin/bash
#set -v 

#cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: service-lb-ipam
  labels:
    color: red
spec:
  type: LoadBalancer
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: DaemonSet
#kind: Deployment
metadata:
  labels:
    color: red
  name: lb-ipam
spec:
  #replicas: 1
  selector:
    matchLabels:
      color: red
  template:
    metadata:
      labels:
        color: red
    spec:
      containers:
      - image: 192.168.2.100:5000/nettool
        name: nettoolbox
        securityContext:
          privileged: true
---
#EOF
