apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: flannel-wireguard
  name: flannel-wireguard
spec:
  selector:
    matchLabels:
      app: flannel-wireguard
  template:
    metadata:
      labels:
        app: flannel-wireguard
    spec:
      containers:
      - image: 192.168.2.100:5000/nettool
        name: nettoolbox
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: serversvc
spec:
  type: NodePort
  selector:
    app: flannel-wireguard
  ports:
  - name: flannel-wireguard
    port: 8080
    targetPort: 80
    nodePort: 32000
