apiVersion: apps/v1
kind: DaemonSet
#kind: Deployment
metadata:
  labels:
    app: cilium-vxlan-host-routing
  name: cilium-vxlan-host-routing
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: cilium-vxlan-host-routing
  template:
    metadata:
      labels:
        app: cilium-vxlan-host-routing
    spec:
      containers:
      - image: 192.168.2.100:5000/nettool
        name: nettoolbox
        securityContext:
          privileged: true

---
apiVersion: v1
kind: Service
metadata:
  name: serversvc
spec:
  type: NodePort
  selector:
    app: cilium-vxlan-host-routing
  ports:
  - name: cni
    port: 8080
    targetPort: 80
    nodePort: 32000
