apiVersion: v1
kind: Pod
metadata:
  name: afxdp-l2fwd
  annotations:
    k8s.v1.cni.cncf.io/networks: afxdp-network
spec:
  containers:
  - name: l2fwd
    image: shivank1128/l2l3fwd
    imagePullPolicy: Never
    command: ["sleep", "infinity"]
    securityContext:
      privileged: true
      capabilities:
        add: ["CAP_SYS_ADMIN"]
    volumeMounts:
    - mountPath: /dev/hugepages
      name: hugepage
    resources:
      requests:
        cpu: "6000m"
        afxdp/myPool: '1'                                          
      limits:                                  
        cpu: "6000m"
        hugepages-1Gi: 2Gi
        afxdp/myPool: '1'                     
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
