apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cc
  name: cc
spec:
  containers:
  - args:
    - /sbin/init
    image: centos:7
    name: cc
    env:
    - name: TZ
      value: "Asia/Shanghai"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
