---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-service-local
  annotations:
    io.cilium/global-service: "true"
    io.cilium/service-affinity: local
spec:
  type: ClusterIP
  selector:
    app: echoserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-service-remote
  annotations:
    io.cilium/global-service: "true"
    io.cilium/service-affinity: remote
spec:
  type: ClusterIP
  selector:
    app: echoserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-service-none
  annotations:
    io.cilium/global-service: "true"
    io.cilium/service-affinity: none
spec:
  type: ClusterIP
  selector:
    app: echoserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: echoserver-daemonset
  labels:
    app: echoserver
spec:
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: echoserver
        image: 192.168.2.100:5000/ealen/echo-server:latest
        env:
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
