apiVersion: v1
kind: ConfigMap
metadata:
  name: afxdp-dp-config
  namespace: kube-system
data:
  config.json: |
    {
        "logLevel":"debug",
        "logFile":"afxdp-dp.log",
        "pools":[
          {
             "name":"eastPool",
             "mode":"primary",
             "drivers":[
                {
                   "name":"e1000",
                   "excludeDevices":[
                    {
                        "name":"ens21"
                    },
                    {
                        "name":"ens22"
                    },
                    {
                        "name":"ens18"
                    }
                    ]
                }
             ]
          },
          {
             "name":"westPool",
             "mode":"primary",
             "drivers":[
                {
                   "name":"e1000",
                   "excludeDevices":[
                    {
                        "name":"ens19"
                    },
                    {
                        "name":"ens20"
                    },
                    {
                        "name":"ens18"
                    }
                    ]
                }
             ]
          }
       ]
    }
